name: Primer workflow

on: push

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "Hola mundo Actions"

      - name: Bajar codigo
        uses: actions/checkout@v5

      - name: Probar codigo
        run: python3 main.py

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ulopeznovoa/holamundo

        
        

        

        

        
